### ISSUE TITLE
cannot work with mode-watcher

### ISSUE THREAD

**Issue by leonwang908** [BearToCode/carta#57]
carta will stop rendering stuff like highlightjs, `<h1>` if I do like below in +layout.svelte

```js
import { ModeWatcher, setMode, resetMode } from 'mode-watcher';
```

btw, is there any easy way to add dual theme like light/dark in carta?

**Comment by BearToCode** [comment]
Hello,

I updated docs to include a simple explanation to implement a dark mode, you can check them out [here](https://beartocode.github.io/carta/editing-styles#dark-mode), but all you have to do is the following:

```css
/* Editor dark mode */
/* Only if you are using the default theme */
html.dark .carta-theme__default {
	--border-color: var(--border-color-dark);
	--selection-color: var(--selection-color-dark);
	--focus-outline: var(--focus-outline-dark);
	--hover-color: var(--hover-color-dark);
	--caret-color: var(--caret-color-dark);
	--text-color: var(--text-color-dark);
}

/* Code dark mode */
/* Only if you didn't specify a custom code theme */
html.dark .shiki,
html.dark .shiki span {
	color: var(--shiki-dark) !important;
}
```

I do not how mode-watcher works, but if it just sets a `class="dark"` to the root `html` element(or `body`...), it should work fine with the instructions explained above.

Let me know if this solved your issue.

**Comment by leonwang908** [comment]
Hello, this one is very helpful for setting dark mode, but I still facing rendering issue.

![image](https://github.com/BearToCode/carta/assets/15900133/34409fe5-d7c7-4d74-8986-30ed9764efcc)
the elements show me `<h1>test</h1>` but looks like there are some css issue that cannot show heading correctly.
do you have any ideas?

**Comment by mjrdd** [comment]
I had the same issue. But I think it is related to tailwind since it clears the default styling.
You have to manually style it since the styling is not included in the default.css.

**Comment by BearToCode** [comment]
There are no embedded styles for the generated HTML. You can write them yourself, or something like [github-markdown-css](https://github.com/sindresorhus/github-markdown-css?tab=readme-ov-file#install)

**Comment by leonwang908** [comment]
after import [github-markdown-css](https://github.com/sindresorhus/github-markdown-css), My app could rendering `h1`. but highlightjs still not working 
![image](https://github.com/BearToCode/carta/assets/15900133/d7ab7afa-05f5-4ab7-bd37-db4d1560ac58)

and I just wondering why my app works with single carta, but if I add it to my layout it will stop working.

**Comment by leonwang908** [comment]
yes, I do added plugin-code
```js
<script>
	import { Carta, MarkdownEditor } from 'carta-md';
	import { code } from '@cartamd/plugin-code';

	import 'carta-md/default.css'; /* Default theme */

	const carta = new Carta({
		sanitizer: false,
		extensions: [code()]
	});

	let value = '';
</script>

<MarkdownEditor {carta} bind:value />

```

it not renderting to highlighted code, just normal code block
![image](https://github.com/BearToCode/carta/assets/15900133/64747550-823f-4eff-9b38-e816df28e14d)

**Comment by BearToCode** [comment]
[Here](https://www.sveltelab.dev/u7adgqi9lurz2kx?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte) is an example with everything, and it's working. Try and see where the differences are. Are you sure you are the latest version of `@cartamd/plugin-code`?

**Comment by leonwang908** [comment]
yes, I am using the latest version of plugin-code. and I can see
 `<style type="text/css" data-vite-dev-id="D:/Dev/example/node_modules/.pnpm/highlight.js@11.9.0/node_modules/highlight.js/styles/github-dark-dimmed.css">hogehoge</style>` in the head

the problem is like carta works well if I put it in a single new svelte project. but if I add +layout.svelte with mode-watcher, a lot of stuffs cannot rendering correctly.

**Comment by BearToCode** [comment]
This is very weird, I think there is something wrong with you config, as highlight.js has nothing to do with this project. And I honestly don't see a way mode-watcher could prevent the actual highlighter, Shiki, from working. 

From your screenshot it looks like the language is not even parsed...

**Comment by leonwang908** [comment]
oh, solved....
I should config a wrong file. (I should config /hogehoge/+page.svelte but actually I did on test/+page.svelte.

Really thanks for you help!
