### ISSUE TITLE
Possibility to disable default styles

### ISSUE THREAD

**Issue by DarthGigi** [BearToCode/carta#98]
Is there a possibility to disable the default styles that come with the editor component?

**Comment by BearToCode** [comment]
The styles that are embedded with the editor component are required to make it work properly. If you really want to overwrite them, you could use `!important` in your styles, but I don't see why you would need that. What are you trying to achieve?

**Comment by DarthGigi** [comment]
I'm trying to achieve a few different things:
1. I'm using carta for a chat component and I need to style it in a specific way
2. I'm using tailwindcss with @apply to try to style the component

I've already tried using `!important` but the styles do not get overridden, especially the inline styles

**Comment by BearToCode** [comment]
I could find a way to avoid using inline styles, would that fix your issue?

**Comment by DarthGigi** [comment]
Is it an idea to do that *and* exclude the default css file by default? So that if someone does want to use the default css they could just `import carta/default.css`?

**Comment by BearToCode** [comment]
Could you make an example of a default style that causes issues? Removing the embedded styles would require everyone to import a new stylesheet, and I'd prefer not to go that way

**Comment by jstjoe** [comment]
I'm not having the same issue, but a related one that might be solved by the same fix. Apologies if this comment should be a separate issue.

At a high level, I'm trying to use carta with PicoCSS: https://picocss.com/
I'm having trouble with a few things including the cursor position and highlighting. I've been tweaking/overriding styles to try to align it but I'm still struggling.

<img width="466" alt="Screenshot 2024-07-05 at 12 08 58 AM" src="https://github.com/BearToCode/carta/assets/2015604/3ccd85ef-9156-4e17-b701-7e2c3c84edfc">

That's with this override:

```
	:global(.carta-font-code *) {
		font-family: '...', monospace;
		font-variant-ligatures: normal !important;
		font-size: 1.1rem;
		line-height: 1.5rem !important;
		padding: 0;
		margin: 0;
	}
```

It was worse when I tried with the documented CSS. This may be a skills issue on my part but it'd be great to have some kind of reset option, or some other kind of compatibility mode?

**Comment by DarthGigi** [comment]
@BearToCode 
> Could you make an example of a default style that causes issues? Removing the embedded styles would require everyone to import a new stylesheet, and I'd prefer not to go that way

For example, I've got the following in my `app.css` file located in `src/`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  .carta-toolbar {
    @apply !hidden;
  }
}
```

However, the toolbar is still visible:
![Screenshot 2024-07-05 at 6  51 35@2x](https://github.com/BearToCode/carta/assets/47110839/31aa72e8-0175-4c82-b180-a819ed0481d0)

I've made a minimal repo: https://stackblitz.com/edit/sveltejs-kit-template-default-sg7wnq

**Comment by BearToCode** [comment]
> I'm not having the same issue, but a related one that might be solved by the same fix. Apologies if this comment should be a separate issue.
> 
> At a high level, I'm trying to use carta with PicoCSS: https://picocss.com/ I'm having trouble with a few things including the cursor position and highlighting. I've been tweaking/overriding styles to try to align it but I'm still struggling.
> <img alt="Screenshot 2024-07-05 at 12 08 58 AM" width="466" src="https://private-user-images.githubusercontent.com/2015604/346007977-3ccd85ef-9156-4e17-b701-7e2c3c84edfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDA3NzksIm5iZiI6MTcyMDIwMDQ3OSwicGF0aCI6Ii8yMDE1NjA0LzM0NjAwNzk3Ny0zY2NkODVlZi05MTU2LTRlMTctYjcwMS03ZTJjM2M4NGVkZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMTcyNzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTNhMjNlOWU5ZGUzYjE2MjY0NjU2YzBiZGUzYTU1YjE0YzRjZDFlMTczODYyNGEzY2NjMzFhMTc1MzM3ODY3OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ksM66A39jMX4r8fUthvkS_O53uG_uTLzp8hM2vKpZIc">
> 
> That's with this override:
> 
> ```
> 	:global(.carta-font-code *) {
> 		font-family: '...', monospace;
> 		font-variant-ligatures: normal !important;
> 		font-size: 1.1rem;
> 		line-height: 1.5rem !important;
> 		padding: 0;
> 		margin: 0;
> 	}
> ```
> 
> It was worse when I tried with the documented CSS. This may be a skills issue on my part but it'd be great to have some kind of reset option, or some other kind of compatibility mode?

Your issue is due to picoCSS setting some styles that cause misalignment in the syntax-highlighting overlay. That should be fixed not by using a custom stylesheet, but by removing those styles. If you want, you can create a new issue with a minimal example so that we can identify which rules are causing the issue

**Comment by BearToCode** [comment]
@DarthGigi 

> @BearToCode
> 
> > Could you make an example of a default style that causes issues? Removing the embedded styles would require everyone to import a new stylesheet, and I'd prefer not to go that way
> 
> For example, I've got the following in my `app.css` file located in `src/`:
> 
> ```css
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> @layer base {
>   .carta-toolbar {
>     @apply !hidden;
>   }
> }
> ```
> 
> However, the toolbar is still visible: ![Screenshot 2024-07-05 at 6  51 35@2x](https://private-user-images.githubusercontent.com/47110839/346185653-31aa72e8-0175-4c82-b180-a819ed0481d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDEyNDksIm5iZiI6MTcyMDIwMDk0OSwicGF0aCI6Ii80NzExMDgzOS8zNDYxODU2NTMtMzFhYTcyZTgtMDE3NS00YzgyLWIxODAtYTgxOWVkMDQ4MWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE3MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1YzZlZDY3MDVjOTlkNmUwMWMwNzU4NGVlODAyNTc0Njc3ZTkxNTJhN2RjNzc3M2IyYjgxODFhNGU2N2M0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qU55jaJDBYJQBJhjQ3J63MJAvXh0kBSavLOzkSgW0CA)
> 
> I've made a minimal repo: https://stackblitz.com/edit/sveltejs-kit-template-default-sg7wnq

You can disable the toolbar by using the [corresponding option](https://beartocode.github.io/carta/api/core#disabletoolbar) in the component:

```svelte
<MarkdownEditor disableToolbar placeholder="Type a message" mode="tabs" {carta} />
```

Also, in your example you did not import a theme, so the editor was broken (You can use `carta-md/default.css` for a default one).

**Comment by DarthGigi** [comment]
@BearToCode 
> You can disable the toolbar by using the [corresponding option](https://beartocode.github.io/carta/api/core#disabletoolbar) in the component:
> 
> ```svelte
> <MarkdownEditor disableToolbar placeholder="Type a message" mode="tabs" {carta} />
> ```
> Also, in your example you did not import a theme, so the editor was broken (You can use `carta-md/default.css` for a default one).

I understand that I can disable the toolbar by using the corresponding option to do so, however, that doesn't fix the issue that tailwindcss classes are not being applied to the component.

Regarding not importing a theme, I'm trying to style everything from scratch myself or is that not possible?

**Comment by BearToCode** [comment]
If you wish to disable the toolbar you should use the dedicated option. For other uses, you can just apply your own styles.
The tailwindCSS style is not working because it's part of the `@layer` directive. By remove it from there, it works just fine.

You can definitely style the editor yourself! That's the same as "[creating your theme](https://beartocode.github.io/carta/editing-styles#customizing-editor-styles)". You can start from copying and editing the [default theme](https://github.com/BearToCode/carta/blob/master/packages/carta-md/src/lib/default.css) or [another one from the examples](https://github.com/BearToCode/carta/tree/master/docs/src/lib/styles).

**Comment by DarthGigi** [comment]
@BearToCode 
> The tailwindCSS style is not working because it's part of the @layer directive. By removing it from there, it works just fine.

That worked indeed, thank you so much! Would you have any idea why it's not working if I wrap it inside a `@layer`? I know that this isn't because of Carta but that it's a tailwind thing

**Comment by BearToCode** [comment]
Glad it fixed your issue! Honestly I'm not sure why it's not working. According to the docs, it should. I'm using tailwind for some projects of mine and I've never had the necessity of using the `@layer` for custom styles, so you can probably just not use them :)

**Comment by DarthGigi** [comment]
@BearToCode 
>  so you can probably just not use them :)

You're right, but for me it feels nicer to have it inside a layer 😅 . The thing is tho that I've got other classes inside `@layer` and those work just fine; weird...

**Comment by BearToCode** [comment]
Maybe that's because the tags referenced from there are only present in a dependency, so they are not picked up from tailwind and not built along with the others, while using the other method they are always present in the output styles.

**Comment by DarthGigi** [comment]
Now that you mention that, adding `"node_modules/carta-md/**/*.{html,js,svelte,ts}"` to the `content` property in the tailwind config file fixes the class not working with `@layer`
